---
# Create a simple VM
# It will create with the default security group which will by rule no outside world access de facto
# So in other to ssh / http to the server it will require configure the proper security groups.

- name: Create a simple VM instance
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy new VM instance
      ec2:
        key_name: mykey
        instance_type: t2.micro
        image: ami-97785bed
        wait: yes
        count: 1
        vpc_subnet_id: subnet-04a18f4f
        assign_public_ip: yes
        region: us-east-1
        instance_tags:
          name: orestes

    - name: Sending confirmation email 
      mail:
        host: smtp.gmail.com
        port: 587
        username: rafael.cardona.it@gmail.com
        password: Sawq1212
        to: John Smith <lab.services.ota@gmail.com>
        subject: Ansible-report
        body: 'System {{ name }} has been successfully provisioned.'
        delegate_to: localhost
