<<<<<<< HEAD
# Here it comes
=======
# Creating simple VPC
>>>>>>> 5fd4742d1d53027234582a8c944fcaa3c595ea94
- name: Create a simple VM instance
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy new VM instance
      ec2_vpc:
        state: present
        cidr_block: 172.23.0.0/16
        resource_tags: { "Environment":"Development" }
        region: us-west-2
