---
# Install and setup http webserver
        
- name: This sets up a httpd webserver
  hosts: all
  connection: ssh
  remote_user: ec2-user
  become_method: sudo
  become: yes
  gather_facts: no
  
  tasks:
    - name: "TRIGGERING FIRST TASK"
    
- name: "Get a state_var"
  manageiq_automate:
    workspace: "{{ workspace }}"
    get_state_var:
    attribute: "e2_ip"
  register: "e2_ip"
  
- name: Real installation a httpd webserver
  hosts: "{{ e2_ip }}"
  tasks:
    - name: Installing HTTPD Server
      yum: 
        name: httpd 
        state: latest
    - name: Restart the HTTPD Service
      service:
        name: httpd 
        state: restarted
