---
# Install and setup http webserver

- name: Comenzando playbook
  hosts: all
  connection: ssh
  remote_user: ec2-user
  become_method: sudo
  become: yes
  gather_facts: no
  connection: local
  tasks:
    - debug:
        msg: "Here starts the seeking"
        
- name: This sets up a httpd webserver
  hosts: "{{ hosts }}"
  connection: ssh
  remote_user: ec2-user
  become_method: sudo
  become: yes
  gather_facts: no
  tasks:
    - name: Installing HTTPD Server
      yum: 
        name: httpd 
        state: latest
    - name: Restart the HTTPD Service
      service:
        name: httpd 
        state: restarted
