---
# Install and setup http webserver

- name: This sets up a httpd webserver
  hosts: "{{ serverInstance }}"
  #hosts: all
  connection: ssh
  remote_user: ec2-user
  become_method : sudo
  become: yes
  gather_facts : yes
  tasks:
    - name : Installing HTTPD Server
      yum : name=httpd state=latest
    - name : Restart the HTTPD Service
      service: name=httpd state=restarted

